### ISSUE TITLE
Kafka Broker is not configurable & defaults to localhost:9092 

### ISSUE THREAD

**Issue by brianraila** [jembi/openhim-core-js#1228]
Trying to use a KAFKA route in my OpenHIM mediator.

I however have my Kafka brokers in a different host. 
I am therefore unable to reach them and keep getting the error below

`
2024-05-17 10:48:28.230 - error: [worker1] KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9092
    at Socket.onError (/app/node_modules/kafkajs/src/network/connection.js:210:23)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
2024-05-17 10:48:28.230 - error: [worker1] [66470bc0d7ff883c08991037] Internal server error occured: KafkaJSNumberOfRetriesExceeded: Connection error: connect ECONNREFUSED 127.0.0.1:9092
`

Looking at the OpenHIM code, it seems like the  default host is localhost.

Is there a way to change this without making changes to the source code itself? 

@rcrichton

**Comment by rcrichton** [comment]
Hi, the kafka broker is configurable in config file - https://github.com/jembi/openhim-core-js/blob/master/config/default.json#L28

You can also supply the `router_kafkaBrokers` env var to set this at runtiume.

**Comment by brianraila** [comment]
Thanks Ryan.
This works.
