### ISSUE TITLE
Public channel transactions fail on rerun

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#408]
Reran transactions from the console and got the following error:
```
info: Rerun Transaction #54eee3975049a77078b5c2fe - HTTP Request is being sent...
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
    ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at rerunHttpRequestSend (/openhim-core-js/lib/api/worker.js:207:14)
    at /openhim-core-js/lib/api/worker.js:58:20
    at rerunSetHTTPRequestOptions (/openhim-core-js/lib/api/worker.js:189:10)
    at Promise.<anonymous> (/openhim-core-js/lib/api/worker.js:46:11)
    at Promise.<anonymous> (/openhim-core-js/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/openhim-core-js/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
```

**Comment by devcritter** [comment]
![screen shot 2015-02-26 at 11 26 06](https://cloud.githubusercontent.com/assets/1872071/6389176/5e9300b0-bdaa-11e4-8cf8-19347c193472.png)

**Comment by devcritter** [comment]
Its not any transaction, but one like above isn't working.

**Comment by devcritter** [comment]
It's only public channel transactions that fail

**Comment by rcrichton** [comment]
Maybe cause of a missing client on the transaction?

**Comment by devcritter** [comment]
Yeah I think you're correct. Maybe for 1.1.0 we should just restrict rerunning from console? it's a simpler check to introduce rather than hotfixing this without any unit tests...

**Comment by rcrichton** [comment]
Do you mean dis-allow re-running of public channels?

**Comment by devcritter** [comment]
Yeah. Unless we think we can get this patched pretty quickly? @debonair?

**Comment by rcrichton** [comment]
I'm ok with putting a restriction on console, but @debonair do you think this will be hard to fix?

**Comment by debonair** [comment]
@rcrichton  I have made a fix just making a pull request now
