### ISSUE TITLE
Mongo Repl failure should not crash HIM (log to file?)

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#467]

**Comment by rcrichton** [comment]
It seems that with the correct mongo uri and mongoose 4.0 the OpenHIM doesn't crash anymore. You have to supply the replicsSet name parameter as follow:

`mongodb://localhost:27017,localhost:27018,localhost:27019/openhim?replicaSet=rs0`

However, it does seems some reads fail during this time. I don't see any indication of writes failing but it seems some transactions get stuck in processing state. This may be because of failed reads before the writes occur or the writes failing silently themselves. I just see the reads failing in the logs:

```
Error: No replica set primary available for query with ReadPreference PRIMARY
      at [object Object].ReplSet.checkoutReader (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:613:14)
      at Cursor.nextObject (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:734:48)
      at Collection.findOne (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
      at NativeCollection.(anonymous function) [as findOne] (/home/ryan/git/openhim-core-js/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:135:28)
      at NodeCollection.findOne (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mquery/lib/collection/node.js:37:19)
      at Query.findOne (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mquery/lib/mquery.js:1664:20)
      at Query.findOne (/home/ryan/git/openhim-core-js/node_modules/mongoose/lib/query.js:1148:22)
      at Function.findOne (/home/ryan/git/openhim-core-js/node_modules/mongoose/lib/model.js:1064:13)
      at exports.authenticateUser (/home/ryan/git/openhim-core-js/src/middleware/basicAuthentication.coffee:40:12)
      at Promise.apply (/home/ryan/git/openhim-core-js/node_modules/q/q.js:1107:26)
```

I'm not sure of the best way to protect against this. Perhaps we should set the readPreference to primaryPreferred so that secondary's can take over the reads during re-election. Writes may still be a problem though.

**Comment by rcrichton** [comment]
It seems with primaryPreferred readPreference I now get the following error:

```
/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/index.js:84
  if(connection && connection.serverCapabilities.hasListIndexesCommand) {
                                                ^
TypeError: Cannot read property 'hasListIndexesCommand' of undefined
    at Collection.listIndexes (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/index.js:84:49)
    at Db.indexInformation (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1608:25)
    at Db.ensureIndex (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1475:8)
    at Collection.ensureIndex (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/index.js:68:11)
    at NativeCollection.(anonymous function) [as ensureIndex] (/home/ryan/git/openhim-core-js/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:135:28)
    at storeVisualizerEvents (/home/ryan/git/openhim-core-js/src/middleware/visualizer.coffee:141:37)
    at [object Object].f [as _onTimeout] (/home/ryan/git/openhim-core-js/src/middleware/visualizer.coffee:151:14)
```

Followed by the workers then failing tor respawn with:

```
/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:565
      internalCallback(error_message, null, server);
      ^
Error: No primary found in set
    at /home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:477:45
    at [object Object].<anonymous> (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:565:7)
    at [object Object].emit (events.js:118:17)
    at [object Object].<anonymous> (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at [object Object].emit (events.js:110:17)
    at Socket.<anonymous> (/home/ryan/git/openhim-core-js/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
```

Then, once the re-election happens, everything continues as normal.

**Comment by rcrichton** [comment]
I'm closing this issue for now, but I think we should think more about how not to loose any data during a re-election. @bausmeier @devcritter What do you guys think?
