### ISSUE TITLE
Exception (primary route) when sending to an invalid secondary route

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#498]
When you've got a channel that points to an offline secondary route (e.g the service is down on that route), the following exception occurs:
> 2015-05-25T08:13:39.029Z - error: [worker2] Internal server error occured: Error: connect ECONNREFUSED 
2015-05-25T08:13:39.029Z - error: [worker2] Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
2015-05-25T08:13:39.029Z - info: [worker2] Storing non primary route responses OpenHIM Mediator Momconnect Validator 2

> /openhim-core-js/src/middleware/stats.coffee:105
  sdc.increment domain + '.channels.' + ctx.authorisedChannel._id + '.nonPrimaryRoutes.' + route.name # Per non-primary route
                                                                                                
> TypeError: Cannot read property 'name' of undefined
    at Object.exports.nonPrimaryRouteRequestCount (/openhim-core-js/src/middleware/stats.coffee:105:97)
    at /openhim-core-js/src/middleware/router.coffee:158:23
    at Query.<anonymous> (/openhim-core-js/src/middleware/messageStore.coffee:112:7)
    at /openhim-core-js/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /openhim-core-js/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:355:11)

Note that this affects the primary response (the worker dies), and the client gets an invalid request response even though the primary route is valid.

**Comment by debonair** [comment]
@devcritter are you using the current master?

**Comment by devcritter** [comment]
@debonair yeah, I am
