### ISSUE TITLE
Packaged openhim-core fails on MongoDB

### ISSUE THREAD

**Issue by litlfred** [jembi/openhim-core-js#553]
I am getting an error on trying to run openhim-core with the Ubuntu packages (1.3.0-5~trusty).  From the /var/log/upstart/openhim-core.log I have:
<pre>
Error
    at Object.<anonymous> (/usr/share/openhim-core/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/share/openhim-core/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Forever detected script exited with code 1
Forever restarting script for 101 time
2015-10-02T16:56:17.798Z - info: [master] Clustering the OpenHIM with 1 workers...

/usr/share/openhim-core/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42
MongoError.prototype = new Error; 
</pre>

**Comment by devcritter** [comment]
Usually that error happens whenever there's an issue connecting to mongo. Can you see if the mongo service is running? If so, could you also check if the mongo connection config looks correct in `/etc/openhim/config.json`?

**Comment by litlfred** [comment]
That was it (thanks for the pointer!)  - mongo was failing to start due to FS limits on Amazon.
Cheers,
-carl

**Comment by devcritter** [comment]
Aah, ok great!
