### ISSUE TITLE
Fix broken dependencies

### ISSUE THREAD

**Issue by devcritter** [jembi/openhim-core-js#579]
The current master is breaking due to mongoose and agenda:

agenda ^0.6.0 gives
> /openhim-core-js/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/openhim-core-js/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/openhim-core-js/node_modules/mongoskin/lib/admin.js:18:37)

Upgrading to ^0.7.0 breaks existing code however
> 2015-11-04T09:32:05.289Z - info: [worker1] Started rerun task processor
 /openhim-core-js/node_modules/agenda/lib/agenda.js:277
    this._collection.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
                    ^
 TypeError: Cannot read property 'findAndModify' of undefined
    at [object Object].Agenda.saveJob (/openhim-core-js/node_modules/agenda/lib/agenda.js:277:21)
    at Job.save (/openhim-core-js/node_modules/agenda/lib/job.js:217:15)
    at createJob (/openhim-core-js/node_modules/agenda/lib/agenda.js:192:9)
    at [object Object].Agenda.every (/openhim-core-js/node_modules/agenda/lib/agenda.js:182:12)
    at Object.setupAgenda (/openhim-core-js/src/alerts.coffee:283:10)
    at startAgenda (/openhim-core-js/src/server.coffee:232:12)
    at /openhim-core-js/src/server.coffee:525:21

mongoose 4.0.2 gives
> Error: Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'
    at Function.Module._resolveFilename (module.js:337:15)

though upgrading to 4.0.3 fixes the problem

**Comment by devcritter** [comment]
Closing this issue for now. The issue only occurs on node version 5 and after discussion it was decided that we will officially only focus on supporting node LTS branches.
