### ISSUE TITLE
Events API testing bug

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-core-js#765]
I encountered this error in travis occasionally:

```
  1) Events API Integration Tests should add mediator info for slow secondary routes:
     Uncaught AssertionError: expected Object {} to have property events
      at Assertion.fail (node_modules/should/cjs/should.js:326:17)
      at Assertion.Object.defineProperty.value [as property] (node_modules/should/cjs/should.js:398:19)
      at Test.<anonymous> (test/integration/eventsAPITests.coffee:307:34)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:908:16
```

**Comment by andrew-w-ross** [comment]
This has finally been fixed.
